"""Add is_archived to Problem

Revision ID: 6c310f67a1f4
Revises: 0fb5aaa68e39
Create Date: 2024-11-26 17:44:42.068742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c310f67a1f4'
down_revision = '0fb5aaa68e39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'problem', ['problem_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.drop_column('is_archived')

# with op.batch_alter_table('file', schema=None) as batch_op:
#     batch_op.drop_constraint('some_constraint', type_='foreignkey')
        batch_op.create_foreign_key(None, 'problem', ['problem_id'], ['id'])

    # ### end Alembic commands ###
